### ISSUE TITLE
SSL Cert invalid

### ISSUE THREAD

**Issue by taenzer** [LeEnno/htwk2ical#19]
There is currently a problem with the SSL certificate on your site (www.htwk-stundenplan.de). Apparently the wrong certificate was selected.

If you access the page via http, images and stylesheets are not loaded because there appears to be an automatic redirect to the https protocol (which is not the case with the homepage).

**Comment by LeEnno** [comment]
Thx for reporting. Unfortunately I can't reproduce it with 3 different browsers. Can you give concrete examples which assets appear to be redirected?

There are no SSL certificates in use because Heroku does not support Free SSL in the Eco plan which I use.

**Comment by taenzer** [comment]
Okay, the fact that there is no certificate explains the error when accessing the page via https.

Now everything is working again for me. The problem was that CSS wasn't loading. Unfortunately I didn't take a screenshot of it either.
